services:
  postgres:
    image: postgres:16-alpine
    container_name: biosense-db
    environment:
      POSTGRES_DB: biosense_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: biosense-mqtt
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
